plugins{
    id 'java'
    id 'war'
}

group = 'com.lms'
version = '1.0.0'
sourceCompatibility = '17'
targetCompatibility = '17'

repositories{
    mavenCentral()
}

dependencies{
    testImplementation 'junit:junit:4.13.2'

    providedCompile 'jakarta.servlet:jakarta.servlet-api:6.0.0'

    implementation 'com.mysql:mysql-connector-j:8.3.0'

    implementation 'org.json:json:20240303'
}

war{
    archiveFileName='LMS.war'
    webAppDirName='src/main/webapp'
}